services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "4000:4000" # This maps your computer's 4000 to the container's 4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=4000 # Tells your Node app to use port 4000
